#!/bin/bash

if [ ! ${EUID:-$(id -u)} -eq 0 ]
then
    echo 'You must be root to run this script (run with sudo)'
    exit 1
fi

installdir=/usr/share/pywal-typora

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    installdir=$HOME/.config/pywal-typora;;
esac

if [ -e $installdir ]
then
	rm -rf $installdir
fi

mkdir $installdir
cp ./config/* $installdir
if [ "${unameOut}" == "Darwin" ]
then
	cp ./pywal-typora /usr/local/bin
else
	cp ./pywal-typora /usr/bin/
fi
